import itertools
perm = list(itertools.permutations([1, 'x1', 2]))
perm2 = list(itertools.permutations([3, 'x2', 4]))
perm3 = list(itertools.permutations([5, 'x3', 6]))
perm4 = list(itertools.permutations([7, 'x4', 8]))
perm5 = list(itertools.permutations([9, 'x5', 10]))
perm6 = list(itertools.permutations([11, 'x6', 12]))
perm7 = list(itertools.permutations([13, 'x7', 14]))
perm8 = list(itertools.permutations([15, 'x8', 16]))
perm9 = list(itertools.permutations([17, 'x9', 18]))
perm10 = list(itertools.permutations([19, 'x10', 20]))
perm11 = list(itertools.permutations([21, 'x11', 22]))
perm12 = list(itertools.permutations([23, 'x12', 24]))
perm13 = list(itertools.permutations([25, 'x13', 26]))

print(list(perm))
print(list(perm2))
print(list(perm3))
print(list(perm4))
print(list(perm5))
print(list(perm6))
print(list(perm7))
print(list(perm8))
print(list(perm9))
print(list(perm10))
print(list(perm11))
print(list(perm12))
print(list(perm13))
